language: rust
after_success: |
  sudo apt-get install binutils-dev libcurl4-openssl-dev libelf-dev libdw-dev &&
  wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz &&
  tar xzf master.tar.gz &&
  mkdir kcov-master/build &&
  cd kcov-master/build &&
  cmake .. &&
  make &&
  sudo make install &&
  cd ../.. &&
  kcov --exclude-pattern=/.cargo --coveralls-id=$TRAVIS_JOB_ID target/kcov target/debug/iomrascalai-*

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/fc22c02441fe92b9dda0
