[package]

name = "iomrascalai"
version = "0.1.6"
authors = ["Urban Hafner <contact@urbanhafner.com>",
        "Thomas Poinsot <thomas.poinsot1@gmail.com>",
        "Igor Polyakov <iopguy+iomrasclai@gmail.com>"]
homepage = "https://github.com/ujh/iomrascalai"
repository = "https://github.com/ujh/iomrascalai"

[dependencies]

getopts         = "*"
rand            = "*"
regex           = "*"
regex_macros    = "*"
rustc-serialize = "*"
strenum         = "*"
time            = "*"