[package]

description = "An AI for the game of Go"
name = "iomrascalai"
version = "0.1.7"
authors = ["Urban Hafner <contact@urbanhafner.com>",
        "Thomas Poinsot <thomas.poinsot1@gmail.com>",
        "Igor Polyakov <iopguy+iomrasclai@gmail.com>"]
homepage = "https://github.com/ujh/iomrascalai"
repository = "https://github.com/ujh/iomrascalai"
license = "GPL-3.0+"

[dependencies]

getopts         = "*"
rand            = "*"
regex           = "*"
regex_macros    = "*"
rustc-serialize = "*"
strenum         = "*"
time            = "*"