[package]

name = "iomrascalai"
version = "0.1.5"
authors = ["Urban Hafner <contact@urbanhafner.com>",
        "Thomas Poinsot <thomas.poinsot1@gmail.com>",
        "Igor Polyakov <iopguy+iomrasclai@gmail.com>"]
homepage = "https://github.com/ujh/iomrascalai"
repository = "https://github.com/ujh/iomrascalai"

[dependencies]

getopts         = "*"
rand            = "*"
regex           = "*"
regex_macros    = "*"
rustc-serialize = "*"
# Temporarily use the github time crate, due to a Windowns bug in the released version
# time            = "*"
strenum         = "*"

[dependencies.time]

git = "https://github.com/rust-lang/time"